name: Build
on:
  push:
    branches: [ main ]
  pull_request:

env:
  DOTNET_VERSION: '7.x'

jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [ 'win-x64', 'linux-x64', 'osx-x64' ]
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Build tool
        run: dotnet build -c Release
        working-directory: ./DiagnosticsAgent
      
      - name: Publish tool
        run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true
        working-directory: ./DiagnosticsAgent
        
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: diagnostics-agent
          path: DiagnosticsAgent/bin/Release/net7.0/${{ matrix.runtime }}/publish/

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run Tests
        run: dotnet test
        working-directory: ./DiagnosticsAgentTests

  inspectCode:
    name: Inspect code
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2023.1.5
        with:
          cache-default-branch-only: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}