name: Build
on:
  push:
    branches: [ main ]
  pull_request:

env:
  DOTNET_VERSION: '7.x'

jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install dependencies
        run: dotnet restore

      - name: Build tool
        run: dotnet build -c Release --no-restore --nologo
        working-directory: ./DiagnosticsAgent

      - name: Publish tool
        run: dotnet publish -c Release --no-restore --no-build --nologo -p:PublishSingleFile=true
        working-directory: ./DiagnosticsAgent

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: diagnostics-agent
          path: DiagnosticsAgent/bin/Release/net7.0/publish/

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run Tests
        run: dotnet test
        working-directory: ./DiagnosticsAgentTests

  inspectCode:
    name: Inspect code
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2023.2.1
        with:
          cache-default-branch-only: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}