name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish NuGet Package
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Pack Project
        run: dotnet pack -c Release --nologo

      - name: Publish NuGet Package
        run: dotnet nuget push DiagnosticsAgent/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
    